name: Custom Build Modules
on: [workflow_call, workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Get last version code
        id: next_ver_code
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          if [ -z "$TAG" ]; then TAG=0; fi
          echo "NEXT_VER_CODE=$((TAG))" >> $GITHUB_OUTPUT

      - name: Build modules/APKs
        run: ./build.sh build
        env:
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}

      - name: Upload Build APKS
        uses: nikhilbadyal/upload-artifact@count-check
        with:
          name: Built-APKs
          path: |
            ./build/*
          if-no-files-found: error
          files-to-expect: ${{ inputs.FILES_TO_EXPECT }}

